# Generated by Django 3.1.3 on 2020-11-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digit',
            old_name='picture',
            new_name='image',
        ),
    ]
