# Generated by Django 3.1.3 on 2020-12-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201201_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digit',
            name='classification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
